server:
  port: 9090
spring:
  thymeleaf:
#    prefix: classpath:/static/
#    suffix: .html
#    mode: HTML
    encoding: UTF-8
    cache: false # TODO 활성화

  datasource:
    url: jdbc:mysql://localhost:3306/design_bytes
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults=false
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
springdoc:
  show-actuator: false

# TODO DELETE
logging:
  level:
    org:
      springframework:
#        web: DEBUG
#        data: DEBUG
        security: debug
#        boot: DEBUG